name: tests

on:
  push:
    branches:
      - main
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.suite_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 'lts'
          - '1'
        moi_suite:
          - '0'
          - '1'
        include:
          - moi_suite: '0'
            suite_name: 'unit'
          - moi_suite: '1'
            suite_name: 'MOI'
    env:
      COOLPDLP_TEST_MOISUITE: ${{ matrix.moi_suite }}
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
